<div class="centered">
	<h1 class="text-contrast in-eyecatcher">Create Blog Post</h1>
</div>
	<?=form_open(NULL, $form['form']);?>
		<div class="centered">
			<div class="nojs-create">
				<?=form_input($form['headline']);?>
				<?=form_textarea($form['text']);?>
			</div>
			<h1 class="editable hidden" id="edit-headline" data-create="headline"><?php if(strlen($form['headline']['value']) > 0): echo $form['headline']['value']; else: ?>Your headline<?php endif; ?></h1>

			<div class="editable hidden" id="edit-body" data-create="text">
			<?php if($result): ?>
<?=$result['body'];?>
			<?php else: ?>
<p>
This content is generated by default.
You can edit this content by simply clicking on it. This is an inline editor.
You can also edit the headline by clicking on it.
</p>
<p>
Please make shure to follow the style-guidelines.
This improves the user-experience because of an normalized interface wich is in every post the same.
Normally you can not break these guidelines if you are not trying on purpose.
The guidelies are following:
</p>
<h2>Style guidelines</h2>
<ol>
	<li>Please use the page-break on long articles. When you use the page-break, the part <strong>before</strong> it will be shown at the blog-site, <strong>the rest</strong> will show up when the user decides to read the full article.</li>
	<li>Use tables only for displaying a bunch of data, not to beautify.</li>
	<li>Please do not overformat your text.</li>
	<li>Please do not use weird alignment.</li>
	<li>Please make shure your uploaded images are in a good resolution.</li>
</ol>
<blockquote>
&quot;Use blogquotes only for quotes.&quot; &mdash; <em>The admin</em>.
</blockquote>
<p>
Now that you have read all this, you can start creating your entry. You can either delete all the content or click at the menubar on File &#8680; New Document.
</p>
			<?php endif; ?>
</div>
		</div>
	<hr />
	<div class="centered">
		<table class="settings">
			<tr>
				<td><?=form_label($form['slug_label']['content'], $form['slug_label']['for'])?></td>
				<td><?=form_input($form['slug'])?></td>
			</tr>
		<?php if(isset($form['enable'])) {
			echo '<tr><td>' . form_label($form['enable_label']['content'], $form['enable_label']['for']) . '</td>';
			echo '<td>' . form_checkbox($form['enable']) . '</td></tr>';
		}
		?>
			<tr>
				<td><?=form_input($form['validate']);?></td>
				<td><?=$form['validate']['title'];?></td>
			</tr>
			<tr>
				<td><?=form_input($form['submit']);?></td>
				<td><?=$form['submit']['title'];?></td>
			</tr>



		</table>
	<?=form_close();?>
	</div>
</div>